export type Product = {
  id: string;
  sku: string;
  name: string;
  shortDesc: string;
  fullDesc: string;
  price: number;
  category: "Living Room" | "Decor" | "Kitchenware" | "Bedding" | "Organization" | "Bathroom";
};

export const products: Product[] = [
  {
    id: "1",
    sku: "CVX-LV-001",
    name: "Aria Velvet Throw Pillow",
    shortDesc: "Soft, luxurious velvet cushion.",
    fullDesc: "Add a touch of luxury to your sofa with the Aria Velvet Throw Pillow. Crafted from premium, fade-resistant velvet, it features a hidden zipper and includes a plush, hypoallergenic insert.",
    price: 24.99,
    category: "Living Room",
  },
  {
    id: "2",
    sku: "CVX-LV-002",
    name: "Calvexa Signature Throw Blanket",
    shortDesc: "Knitted warm throw blanket.",
    fullDesc: "Snuggle up in style with our chunky knit throw. Made from 100% breathable cotton, this blanket is perfect for all-season comfort and adds rich texture to any bed or couch.",
    price: 45.00,
    category: "Living Room",
  },
  {
    id: "3",
    sku: "CVX-DC-001",
    name: "Lumière Minimalist Table Lamp",
    shortDesc: "Sleek, modern desk/table lighting.",
    fullDesc: "Illuminate your space with the Lumière Table Lamp. Featuring a matte black metal base and a warm fabric shade, it provides the perfect ambient lighting for reading or relaxing.",
    price: 68.50,
    category: "Decor",
  },
  {
    id: "4",
    sku: "CVX-KT-001",
    name: "Artisan Ceramic Dinner Set (16pcs)",
    shortDesc: "Hand-glazed dining set for 4.",
    fullDesc: "Elevate your dining experience with this 16-piece artisan set. Includes dinner plates, salad plates, bowls, and mugs, all featuring a unique, scratch-resistant reactive glaze finish.",
    price: 110.00,
    category: "Kitchenware",
  },
  {
    id: "5",
    sku: "CVX-KT-002",
    name: "Bamboo Cutting Board Trio",
    shortDesc: "Set of 3 sustainable chopping boards.",
    fullDesc: "Prep meals effortlessly with our eco-friendly bamboo boards. Naturally antimicrobial and knife-friendly, this set includes three versatile sizes with built-in juice grooves.",
    price: 32.99,
    category: "Kitchenware",
  },
  {
    id: "6",
    sku: "CVX-BD-001",
    name: "Cloud-Soft Egyptian Cotton Sheets",
    shortDesc: "400-thread count luxury bedsheets.",
    fullDesc: "Drift into perfect sleep with our 100% Egyptian cotton sheet set. Highly breathable, incredibly soft, and designed to get even softer with every single wash. Includes fitted, flat, and 2 pillowcases.",
    price: 89.00,
    category: "Bedding",
  },
  {
    id: "7",
    sku: "CVX-DC-002",
    name: "Zenith Aromatherapy Diffuser",
    shortDesc: "Ultrasonic essential oil diffuser.",
    fullDesc: "Transform your home into a spa. The Zenith Diffuser features a sleek ceramic cover, 7 ambient light settings, and ultra-quiet operation to perfectly disperse your favorite scents.",
    price: 38.00,
    category: "Decor",
  },
  {
    id: "8",
    sku: "CVX-LV-003",
    name: "Natura Woven Storage Baskets",
    shortDesc: "Set of 2 seagrass baskets.",
    fullDesc: "Keep your space tidy and stylish. Handwoven from natural seagrass, these durable baskets are perfect for storing blankets, toys, or magazines while adding a bohemian touch to your decor.",
    price: 42.50,
    category: "Organization",
  },
  {
    id: "9",
    sku: "CVX-KT-003",
    name: "Chef's Choice Stainless Knife Set",
    shortDesc: "6-piece premium kitchen knives with block.",
    fullDesc: "Slice and dice like a pro. Forged from high-carbon stainless steel, these precisely weighted knives come nestled in a beautiful acacia wood block for safe, stylish storage.",
    price: 95.00,
    category: "Kitchenware",
  },
  {
    id: "10",
    sku: "CVX-BT-001",
    name: "Plush Memory Foam Bath Mat",
    shortDesc: "Ultra-absorbent, slip-resistant mat.",
    fullDesc: "Step out of the shower and onto a cloud. This thick memory foam bath mat absorbs water instantly and features a durable, non-slip rubber backing for ultimate safety.",
    price: 22.00,
    category: "Bathroom",
  },
  {
    id: "11",
    sku: "CVX-DC-003",
    name: "Elegance Glass Vase",
    shortDesc: "Hand-blown geometric flower vase.",
    fullDesc: "Display your florals beautifully. This heavy-bottomed, geometrically faceted glass vase catches the light perfectly, making it a stunning centerpiece even when empty.",
    price: 28.50,
    category: "Decor",
  },
  {
    id: "12",
    sku: "CVX-LV-004",
    name: "Ergo-Rest Lumbar Cushion",
    shortDesc: "Supportive memory foam back cushion.",
    fullDesc: "Upgrade your home office or favorite armchair. Our ergonomically designed lumbar cushion promotes proper posture and relieves lower back tension during long periods of sitting.",
    price: 35.00,
    category: "Living Room",
  },
  {
    id: "13",
    sku: "CVX-KT-004",
    name: "Cast Iron Dutch Oven (5.5 Qt)",
    shortDesc: "Enameled heavy-duty cooking pot.",
    fullDesc: "The ultimate kitchen workhorse. Whether you are baking bread or simmering stews, this enameled cast iron Dutch oven ensures even heat distribution and unmatched durability.",
    price: 125.00,
    category: "Kitchenware",
  },
  {
    id: "14",
    sku: "CVX-BT-002",
    name: "Serenity Bamboo Bath Caddy",
    shortDesc: "Expandable over-tub tray.",
    fullDesc: "Take your bath to the next level. This water-resistant bamboo caddy holds your book, tablet, wine glass, and soap, adjusting to fit almost any bathtub width perfectly.",
    price: 48.00,
    category: "Bathroom",
  },
  {
    id: "15",
    sku: "CVX-DC-004",
    name: "Botanica Faux Potted Plant",
    shortDesc: "Lifelike artificial indoor greenery.",
    fullDesc: "Bring the outdoors in, zero maintenance required. This highly realistic faux monstera plant comes in a modern ceramic pot, adding an instant pop of life and vibrant green to any dark corner.",
    price: 55.00,
    category: "Decor",
  },
];